---
- name: Choose Steps
  hosts:  all
  become: yes
  become_user: root

  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: installed

  - name: Start httpd
    systemd:
      name: httpd
      state: started

  - name: Install telnet
    yum:
      name: telnet
      state: present

...
