---
- name: Setup Apache server
  hosts: localhost
  
  tasks:
    - name: Install httpd
      yum:
        name: httpd
      tags: i-httpd

    - name: Start httpd
      systemd:
        name: httpd
        state: started
      tags: s-httpd

...
