---
- name: Install packages through loop
  hosts: all
  vars:
    packages: [ftp,telnet,htop]
  become: true
  become_user: root

  tasks:
    - name: Install packages
      yum:
        name: "{{ packages }}"
        state: present

...
