---
- name: Create and mount new storage
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Create new partition
      parted:
        name: files
        label: gpt
        device: /dev/xvda
        number: 2
        state: present
        part_start: 8590MiB
        part_end: 9590MiB

    - name: Create xfs filesystem
      filesystem:
        dev: /dev/xvda2
        fstype: xfs

    - name: Create mount directory
      file:
        path: /data
        state: directory

    - name: mount the filesystem
      mount:
        src: /dev/xvda2
        fstype: xfs
        state: mounted
        path: /data

...
