---
- name: Installing and Running mariadb-server
  hosts: localhost
  become: yes
  become_user: root

  tasks:
  - name: Install mariadb-server
    apt:
      name: mariadb-server
      state: present

  - name: start mariadb
    service:
      name: mariadb
      state: started
...
