---
- name: Add or Update user password
  hosts: client_1
  become: true
  become_user: root

  tasks:
  - name: Change george password
    user:
      name: george
      update_password: always
      password: "{{ new_password|password_hash('sha512') }}"
...
