---
- name: Create users through loop
  hosts: localhost
  become: true
  become_user: root

  vars: 
    users: [jerry,kramer, eliane]

  tasks:
    - name: Create users
      user:
        name: "{{ item }}"
      with_items: "{{ users }}"

...
